# Generated by Django 3.1.6 on 2021-02-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('prediction1', models.CharField(blank=True, max_length=200)),
                ('prediction2', models.CharField(blank=True, max_length=200)),
                ('prediction3', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
