# Generated by Django 3.1.6 on 2021-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210206_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='url',
            field=models.FileField(upload_to='pictures'),
        ),
    ]
