# Generated by Django 3.1.6 on 2021-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210206_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='url',
            field=models.URLField(),
        ),
    ]
